- name: create a unique temp container name
  set_fact:
    temp_container_name: nginx_image_{{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}

- name: check for existence of our base image
  shell: "docker images | grep nginx-base-image | grep 1.0"
  ignore_errors: yes
  register: image_check

- set_fact:
    base_image: "{{'nginx-base-image:1.0' if image_check.rc == 0 else 'library/alpine:latest'}}"

- name: build site by running ansible in a docker container
  command: "docker run
    -v /tmp/site:/site
    -w /site
    --name={{temp_container_name}}
    {{base_image}}
    ansible-playbook --check nginx-playbook.yml local"

- name: create a docker image from the container
  command: "docker commit
    -c 'EXPOSE 80'
    -c 'CMD [\"nginx\", \"-g\", \"daemon off;\"]'
    {{temp_container_name}}
    nginx-base-image:1.0"

- name: delete the container once the image has been successfully built
  command: docker rm -f -v {{temp_container_name}}