- name: create a unique temp container name
  set_fact:
    temp_container_name: nginx_container_{{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}

# To confirm that I used the official alpine linux image, here is
# a reference to the url: https://hub.docker.com/_/alpine
- name: build site by running ansible in a docker container
  command: "docker run
    -v /tmp/site:/site
    -w /site
    --name={{temp_container_name}}
    alpine:latest
    ansible-playbook nginx-playbook.yml -c local"

- name: create a docker image from the container
  command: "docker commit
    -c 'EXPOSE 80'
    -c 'CMD [\"nginx\", \"-g\", \"daemon off;\"]'
    {{temp_container_name}}
    ansible-nginx:1.0"

- name: delete the container once the image has been successfully built
  command: docker rm -f -v {{temp_container_name}}